mpstockadv_admin_stockadv:
  path: /admin/mpstockadv
  controller: MpSoft\MpStockAdv\Controller\Admin\AdminStockAdvController::index
  methods: [GET]

mpstockadv_admin_stockadv_product_search:
  path: /admin/mpstockadv/product-search
  controller: MpSoft\MpStockAdv\Controller\Admin\AdminStockAdvController::productSearchAction
  methods: [GET]

mpstockadv_admin_stockadv_get_states:
  path: /admin/mpstockadv/get-states
  controller: MpSoft\MpStockAdv\Controller\Admin\AdminStockAdvController::getStatesAction
  methods: [GET]

mpstockadv_admin_stockadv_mvt_reasons:
  path: /admin/mpstockadv/mvt-reasons
  controller: MpSoft\MpStockAdv\Controller\Admin\AdminStockAdvController::getMvtReasonsAction
  methods: [GET]

mpstockadv_admin_stockadv_index:
  path: /admin/mpstockadv
  controller: MpSoft\MpStockAdv\Controller\Admin\AdminStockAdvController::index
  methods: [GET]

mpstockadv_admin_warehouse:
  path: /admin/mpstockadv/warehouse
  controller: MpSoft\MpStockAdv\Controller\Admin\WarehouseController::index
  methods: [GET]

mpstockadv_admin_warehouse_edit:
  path: /admin/mpstockadv/warehouse/edit/{id}
  controller: MpSoft\MpStockAdv\Controller\Admin\WarehouseController::edit
  methods: [GET, POST]

mpstockadv_admin_stockmovement:
  path: /admin/mpstockadv/stock-movement
  controller: MpSoft\MpStockAdv\Controller\Admin\StockMovementController::index
  methods: [GET]

mpstockadv_admin_stockadv_render_form:
  path: /admin/mpstockadv/render-form
  controller: MpSoft\MpStockAdv\Controller\Admin\StockMvtController::renderFormAction
  methods: [GET]

mpstockadv_admin_stockentry:
  path: /admin/mpstockadv/stock-entry
  controller: MpSoft\MpStockAdv\Controller\Admin\StockEntryController::index
  methods: [GET]

mpstockadv_admin_stockexit:
  path: /admin/mpstockadv/stock-exit
  controller: MpSoft\MpStockAdv\Controller\Admin\StockExitController::index
  methods: [GET]

mpstockadv_admin_stockview:
  path: /admin/mpstockadv/stock-view
  controller: MpSoft\MpStockAdv\Controller\Admin\StockViewController::index
  methods: [GET]

mpstockadv_admin_stockview_redirect:
  path: /admin/mpstockadv/stock-view/redirect
  controller: MpSoft\MpStockAdv\Controller\Admin\StockViewController::redirectToStockView
  methods: [GET]

mpstockadv_admin_stockview_default_qty:
  path: /admin/mpstockadv/stock-view/default-qty
  controller: MpSoft\MpStockAdv\Controller\Admin\StockViewController::defaultQtyAction
  methods: [GET]

mpstockadv_admin_stockview_set_default:
  path: /admin/mpstockadv/stock-view/set-default/{id_product_attribute}
  controller: MpSoft\MpStockAdv\Controller\Admin\StockViewController::setDefaultCombinationAction
  methods: [GET]

mpstockadv_admin_mvtreasons_index:
  path: /admin/mpstockadv/mvt-reasons
  controller: MpSoft\MpStockAdv\Controller\Admin\StockMvtReasonsController::index
  methods: [GET]

mpstockadv_admin_mvtreasons_list:
  path: /admin/mpstockadv/mvt-reasons/list
  controller: MpSoft\MpStockAdv\Controller\Admin\StockMvtReasonsController::list
  methods: [GET, POST]

mpstockadv_admin_mvtreasons_save:
  path: /admin/mpstockadv/mvt-reasons/save
  controller: MpSoft\MpStockAdv\Controller\Admin\StockMvtReasonsController::save
  methods: [POST]

mpstockadv_admin_supplyorders:
  path: /admin/mpstockadv/supply-orders
  controller: MpSoft\MpStockAdv\Controller\Admin\StockSupplyOrderController::index
  methods: [GET]

mpstockadv_admin_supplyorders_edit:
  path: /admin/mpstockadv/supply-orders/edit/{id}
  controller: MpSoft\MpStockAdv\Controller\Admin\StockSupplyOrderController::edit
  methods: [GET, POST]

mpstockadv_admin_supplyorders_receive:
  path: /admin/mpstockadv/supply-orders/receive/{id}
  controller: MpSoft\MpStockAdv\Controller\Admin\StockSupplyOrderController::receive
  methods: [POST]

mpstockadv_admin_supplyorders_create:
  path: /admin/mpstockadv/supply-orders/create
  controller: MpSoft\MpStockAdv\Controller\Admin\StockSupplyOrderController::create
  methods: [POST]

mpstockadv_admin_supplyorders_product_search:
  path: /admin/mpstockadv/supply-orders/product-search
  controller: MpSoft\MpStockAdv\Controller\Admin\StockSupplyOrderController::productSearch
  methods: [GET]

mpstockadv_admin_mvtreasons_delete:
  path: /admin/mpstockadv/mvt-reasons/delete
  controller: MpSoft\MpStockAdv\Controller\Admin\StockMvtReasonsController::delete
  methods: [POST]

mpstockadv_admin_stockimportexport_import_mvt_reason:
  path: /admin/mpstockadv/import/mvt-reason
  controller: MpSoft\MpStockAdv\Controller\Admin\StockImportExportController::importMvtReason
  methods: [POST]

mpstockadv_admin_stockimportexport_import_orders:
  path: /admin/mpstockadv/import/orders
  controller: MpSoft\MpStockAdv\Controller\Admin\StockImportExportController::importOrders
  methods: [POST]

mpstockadv_admin_stockimportexport_import_xml:
  path: /admin/mpstockadv/import/xml
  controller: MpSoft\MpStockAdv\Controller\Admin\StockImportExportController::importXml
  methods: [POST]

mpstockadv_supply_orders_product_search:
  path: /admin/mpstockadv/supply-orders/product-search
  controller: MpSoft\MpStockAdv\Controller\Admin\StockSupplyOrderController::productSearch
  methods: [GET]

mpstockadv_admin_stockmvt:
  path: /admin/mpstockadv/stock-mvt
  controller: MpSoft\MpStockAdv\Controller\Admin\StockMvtController::indexAction
  methods: [GET]

mpstockadv_admin_stockmvt_ajax_save:
  path: /admin/module/mpstockadv/stockmvt/ajax-save
  methods: [POST]
  defaults:
    _controller: 'MpSoft\MpStockAdv\Controller\Admin\StockMvtController::ajaxSaveAction'

mpstockadv_admin_stockmvt_ajax_get_orders:
  path: /admin/module/mpstockadv/stockmvt/ajax-get-orders
  methods: [POST]
  defaults:
    _controller: 'MpSoft\MpStockAdv\Controller\Admin\StockMvtController::getOrdersAction'

mpstockadv_admin_stockmvt_ajax_get_valid_orders_state:
  path: /admin/module/mpstockadv/stockmvt/ajax-get-valid-orders-state
  methods: [GET]
  defaults:
    _controller: 'MpSoft\MpStockAdv\Controller\Admin\StockMvtController::getValidOrderStatesAction'

mpstockadv_admin_stockmvt_ajax_import_orders_mvt:
  path: /admin/module/mpstockadv/stockmvt/ajax-import-orders-mvt
  methods: [POST]
  defaults:
    _controller: 'MpSoft\MpStockAdv\Controller\Admin\StockMvtController::importOrdersMvtAction'

mpstockadv_admin_stockmvt_ajax_reasons:
  path: /admin/module/mpstockadv/stockmvt/ajax-reasons
  methods: [GET]
  defaults:
    _controller: 'MpSoft\MpStockAdv\Controller\Admin\StockMvtController::ajaxReasonsAction'

mpstockadv_admin_stocksettings:
  path: /admin/mpstockadv/stock-settings
  controller: MpSoft\MpStockAdv\Controller\Admin\AdminStockSettingsController::index
  methods: [GET, POST]

mpstockadv_admin_stockmvt_save_mvt:
  path: /admin/module/mpstockadv/stockmvt/save-mvt
  controller: MpSoft\MpStockAdv\Controller\Admin\StockMvtController::saveMvtAction
  methods: [POST]

mpstockadv_admin_stockmvt_truncate_tables:
  path: /admin/module/mpstockadv/stockmvt/truncate-tables
  controller: MpSoft\MpStockAdv\Controller\Admin\StockMvtController::truncateTablesAction
  methods: [GET]

mpstockadv_admin_stockmvt_get_json_init_stock:
  path: /admin/module/mpstockadv/stockmvt/get-json-init-stock
  controller: MpSoft\MpStockAdv\Controller\Admin\StockMvtController::getJsonInitStockAction
  methods: [GET]

mpstockadv_admin_stockmvt_import_init_stock:
  path: /admin/module/mpstockadv/stockmvt/import-init-stock
  controller: MpSoft\MpStockAdv\Controller\Admin\StockMvtController::importInitStockAction
  methods: [POST]

mpstockadv_controller_stockmvt_index:
  path: /admin/module/mpstockadv/stockmvt
  controller: MpSoft\MpStockAdv\Controllers\StockMvtController::indexAction
  methods: [GET]

mpstockadv_controller_stockmvt_refresh_table_data:
  path: /admin/module/mpstockadv/stockmvt/refresh-table-data
  controller: MpSoft\MpStockAdv\Controllers\StockMvtController::refreshTableDataAction
  methods: [GET]

mpstockadv_controller_stockmvt_load_modal_dialog:
  path: /admin/module/mpstockadv/stockmvt/load-modal-dialog
  controller: MpSoft\MpStockAdv\Controllers\StockMvtController::loadModalMovementsAction
  methods: [GET]

mpstockadv_controller_stockmvt_preferences:
  path: /admin/module/mpstockadv/stockmvt/preferences
  controller: MpSoft\MpStockAdv\Controllers\StockMvtPreferences::indexAction
  methods: [GET]

mpstockadv_controller_stockmvt_load_modal_preferences:
  path: /admin/module/mpstockadv/stockmvt/load-preferences
  controller: MpSoft\MpStockAdv\Controllers\StockMvtPreferences::loadModalPreferencesAction
  methods: [GET]

mpstockadv_controller_stockmvt_save_preferences:
  path: /admin/module/mpstockadv/stockmvt/save-preferences
  controller: MpSoft\MpStockAdv\Controllers\StockMvtPreferences::savePreferencesAction
  methods: [POST]

mpstockadv_controller_stockmvt_product_autocomplete:
  path: /admin/module/mpstockadv/stockmvt/product-autocomplete
  controller: MpSoft\MpStockAdv\Controllers\StockMvtController::searchAction
  methods: [GET, POST]

mpstockadv_controller_stockmvt_product_autocomplete_save:
  path: /admin/module/mpstockadv/stockmvt/product-autocomplete-save
  controller: MpSoft\MpStockAdv\Controllers\StockMvtController::updateStockManagerAction
  methods: [POST]

mpstockadv_controller_stockmvt_load_stock_mvt_preferences:
  path: /admin/module/mpstockadv/stockmvt/load-stock-mvt-preferences
  controller: MpSoft\MpStockAdv\Controllers\StockMvtPreferences::loadStockMvtPreferencesAction
  methods: [GET]

mpstockadv_controller_stockmvt_ajax_refresh_table:
  path: /admin/module/mpstockadv/stockmvt/ajax-process-refresh-table
  controller: MpSoft\MpStockAdv\Controllers\StockMvtController::ajaxProcessRefreshTableMovements
  methods: [POST]

mpstockadv_controller_stockmvt_ajax_truncate_stock_tables_url:
  path: /admin/module/mpstockadv/stockmvt/ajax-truncate-stock-tables
  controller: MpSoft\MpStockAdv\Helpers\ImportFromStockAvailableHelper::truncateStockTablesAction
  methods: [GET]

mpstockadv_controller_stockmvt_ajax_get_stock_available_rows:
  path: /admin/module/mpstockadv/stockmvt/ajax-get-stock-available-rows
  controller: MpSoft\MpStockAdv\Helpers\ImportFromStockAvailableHelper::getStockAvailableRowsAction
  methods: [GET]

mpstockadv_controller_stockmvt_ajax_import_chunk_url:
  path: /admin/module/mpstockadv/stockmvt/ajax-import-chunk
  controller: MpSoft\MpStockAdv\Helpers\ImportFromStockAvailableHelper::importChunkAction
  methods: [POST]

mpstockadv_admin_stockimportexport:
  path: /admin/mpstockadv/stock-import-export
  controller: MpSoft\MpStockAdv\Controllers\StockImportExportController::index
  methods: [GET]

mpstockadv_controller_stockimportexport_parse_xml:
  path: /admin/mpstockadv/stock-import-export/parse-xml
  controller: MpSoft\MpStockAdv\Controllers\StockImportExportController::parseXmlAction
  methods: [POST]

mpstockadv_controller_stockimportexport_import_xml:
  path: /admin/mpstockadv/stock-import-export/import-xml
  controller: MpSoft\MpStockAdv\Helpers\StockMvtImportHelper::importXmlAction
  methods: [POST]
