services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  MpSoft\MpStockAdv\Controller\Admin\:
    resource: "../src/Controller/Admin"
    public: true
    tags: ["controller.service_arguments"]

  # ImportService
  MpSoft\MpStockAdv\Services\StockMvtInitStockImporterService:
    arguments:
      $connection: "@doctrine.dbal.default_connection"
      $legacyContext: "@prestashop.adapter.legacy.context"
      $twig: "@twig"

  MpSoft\MpStockAdv\Controllers\StockMvtPreferences:
    tags: ["controller.service_arguments"]
    public: true

  MpSoft\MpStockAdv\Services\StockProductsService:
    arguments:
      $connection: "@doctrine.dbal.default_connection"
      $context: "@prestashop.adapter.legacy.context"
    public: true

  mpsoft.mpstockadv.services.stockproductsservice:
    alias: 'MpSoft\MpStockAdv\Services\StockProductsService'
    public: true

  MpSoft\MpStockAdv\Services\StockMvtDatatableService:
    arguments:
      $connection: "@doctrine.dbal.default_connection"
      $context: "@prestashop.adapter.legacy.context"
    public: true
