services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  MpSoft\MpStockAdv\Controller\Admin\:
    resource: "../src/Controller/Admin"
    public: true
    tags: ["controller.service_arguments"]

  # ImportService
  MpSoft\MpStockAdv\Services\StockMvtInitStockImporterService:
    arguments:
      $connection: "@doctrine.dbal.default_connection"
      $legacyContext: "@prestashop.adapter.legacy.context"
      $twig: "@twig"
