services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  MpSoft\MpStockAdv\Controller\Admin\:
    resource: "../src/Controller/Admin"
    public: true
    tags: ["controller.service_arguments"]

  # ImportService
  MpSoft\MpStockAdv\Services\StockMvtInitStockImporterService:
    arguments:
      $connection: "@doctrine.dbal.default_connection"
      $legacyContext: "@prestashop.adapter.legacy.context"
      $twig: "@twig"

  MpSoft\MpStockAdv\Services\MenuDataService:
    arguments:
      $router: "@router"
      $context: "@prestashop.adapter.legacy.context"
      $twig: "@twig"
    public: true

  MpSoft\MpStockAdv\Services\MpStockAdvConfiguration:
    arguments:
      $router: "@router"
      $context: "@prestashop.adapter.legacy.context"
      $connection: "@doctrine.dbal.default_connection"

  MpSoft\MpStockAdv\Controllers\StockMvtPreferences:
    tags: ["controller.service_arguments"]
    public: true

  MpSoft\MpStockAdv\Services\ProductAutocompleteService:
    arguments:
      $connection: "@doctrine.dbal.default_connection"
      $context: "@prestashop.adapter.legacy.context"
    public: true
